name: code format check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources 
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Run dotnet-format
      run: dotnet-format --fix-analyzers info --fix-style info --check
